changed code to support variants and flavors. Flavors are supposed to be slightly different configurations of the same variant, where as variants can be very different from the default OctoPi release:  * added a variants directory with an example  * moved common functions to util.sh

diff --git a/src/build b/src/build
--- a/src/build
+++ b/src/build
@@ -1,4 +1,32 @@
 #!/usr/bin/env bash
+
+source ./util.sh
+
 OCTOPI_PATH=$(dirname $(realpath -s $0))
+
+BUILD_VARIANT=default
+BUILD_FLAVOR=default
+
+if [ "$#" -eq 1 ]; then
+  BUILD_VARIANT=$1
+elif [ "$#" -eq 2 ]; then
+  BUILD_VARIANT=$1
+  BUILD_FLAVOR=$2
+fi
+
+if [ $BUILD_VARIANT != 'default' ]; then
+  export VARIANT_BASE="$OCTOPI_PATH/variants/$BUILD_VARIANT"
+  [ -d $VARIANT_BASE ] || die "Could not find Variant $BUILD_VARIANT"
+  if [ $BUILD_FLAVOR == '' ] || [ $BUILD_FLAVOR == 'default' ]; then
+    FLAVOR_CONFIG=$VARIANT_BASE/config
+  else
+    FLAVOR_CONFIG=$VARIANT_BASE/config.$BUILD_FLAVOR
+  fi
+  source $FLAVOR_CONFIG || die "Could not find config file $FLAVOR_CONFIG"
+
+  echo "Building VARIANT $BUILD_VARIANT, FLAVOR $BUILD_FLAVOR"
+fi
+
+
 source $OCTOPI_PATH/config
 source $OCTOPI_PATH/octopi
